/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore16CreateInput } from "./Operatore16CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore16Args {
  @ApiProperty({
    required: true,
    type: () => Operatore16CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore16CreateInput)
  @Field(() => Operatore16CreateInput, { nullable: false })
  data!: Operatore16CreateInput;
}

export { CreateOperatore16Args as CreateOperatore16Args };
