/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore16WhereUniqueInput } from "./Operatore16WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore16UpdateInput } from "./Operatore16UpdateInput";

@ArgsType()
class UpdateOperatore16Args {
  @ApiProperty({
    required: true,
    type: () => Operatore16WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore16WhereUniqueInput)
  @Field(() => Operatore16WhereUniqueInput, { nullable: false })
  where!: Operatore16WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore16UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore16UpdateInput)
  @Field(() => Operatore16UpdateInput, { nullable: false })
  data!: Operatore16UpdateInput;
}

export { UpdateOperatore16Args as UpdateOperatore16Args };
