/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore1WhereInput } from "./Operatore1WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore1CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore1WhereInput,
  })
  @Field(() => Operatore1WhereInput, { nullable: true })
  @Type(() => Operatore1WhereInput)
  where?: Operatore1WhereInput;
}

export { Operatore1CountArgs as Operatore1CountArgs };
