/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore12CreateInput } from "./Operatore12CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore12Args {
  @ApiProperty({
    required: true,
    type: () => Operatore12CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore12CreateInput)
  @Field(() => Operatore12CreateInput, { nullable: false })
  data!: Operatore12CreateInput;
}

export { CreateOperatore12Args as CreateOperatore12Args };
