/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore12WhereInput } from "./Operatore12WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore12OrderByInput } from "./Operatore12OrderByInput";

@ArgsType()
class Operatore12FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore12WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore12WhereInput, { nullable: true })
  @Type(() => Operatore12WhereInput)
  where?: Operatore12WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore12OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore12OrderByInput], { nullable: true })
  @Type(() => Operatore12OrderByInput)
  orderBy?: Array<Operatore12OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore12FindManyArgs as Operatore12FindManyArgs };
