/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore2WhereInput } from "./Operatore2WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore2CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore2WhereInput,
  })
  @Field(() => Operatore2WhereInput, { nullable: true })
  @Type(() => Operatore2WhereInput)
  where?: Operatore2WhereInput;
}

export { Operatore2CountArgs as Operatore2CountArgs };
