/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore8CreateInput } from "./Operatore8CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore8Args {
  @ApiProperty({
    required: true,
    type: () => Operatore8CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore8CreateInput)
  @Field(() => Operatore8CreateInput, { nullable: false })
  data!: Operatore8CreateInput;
}

export { CreateOperatore8Args as CreateOperatore8Args };
