/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore8Service } from "../operatore8.service";
import { Operatore8CreateInput } from "./Operatore8CreateInput";
import { Operatore8 } from "./Operatore8";
import { Operatore8FindManyArgs } from "./Operatore8FindManyArgs";
import { Operatore8WhereUniqueInput } from "./Operatore8WhereUniqueInput";
import { Operatore8UpdateInput } from "./Operatore8UpdateInput";

export class Operatore8ControllerBase {
  constructor(protected readonly service: Operatore8Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore8 })
  async createOperatore8(
    @common.Body() data: Operatore8CreateInput
  ): Promise<Operatore8> {
    return await this.service.createOperatore8({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore8] })
  @ApiNestedQuery(Operatore8FindManyArgs)
  async operatore8s(@common.Req() request: Request): Promise<Operatore8[]> {
    const args = plainToClass(Operatore8FindManyArgs, request.query);
    return this.service.operatore8s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore8 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore8(
    @common.Param() params: Operatore8WhereUniqueInput
  ): Promise<Operatore8 | null> {
    const result = await this.service.operatore8({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore8 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore8(
    @common.Param() params: Operatore8WhereUniqueInput,
    @common.Body() data: Operatore8UpdateInput
  ): Promise<Operatore8 | null> {
    try {
      return await this.service.updateOperatore8({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore8 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore8(
    @common.Param() params: Operatore8WhereUniqueInput
  ): Promise<Operatore8 | null> {
    try {
      return await this.service.deleteOperatore8({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
