/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore8WhereInput } from "./Operatore8WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore8ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore8WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore8WhereInput)
  @IsOptional()
  @Field(() => Operatore8WhereInput, {
    nullable: true,
  })
  every?: Operatore8WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore8WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore8WhereInput)
  @IsOptional()
  @Field(() => Operatore8WhereInput, {
    nullable: true,
  })
  some?: Operatore8WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore8WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore8WhereInput)
  @IsOptional()
  @Field(() => Operatore8WhereInput, {
    nullable: true,
  })
  none?: Operatore8WhereInput;
}
export { Operatore8ListRelationFilter as Operatore8ListRelationFilter };
