/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore8WhereUniqueInput } from "./Operatore8WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore8UpdateInput } from "./Operatore8UpdateInput";

@ArgsType()
class UpdateOperatore8Args {
  @ApiProperty({
    required: true,
    type: () => Operatore8WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore8WhereUniqueInput)
  @Field(() => Operatore8WhereUniqueInput, { nullable: false })
  where!: Operatore8WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore8UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore8UpdateInput)
  @Field(() => Operatore8UpdateInput, { nullable: false })
  data!: Operatore8UpdateInput;
}

export { UpdateOperatore8Args as UpdateOperatore8Args };
