/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore22CreateInput } from "./Operatore22CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore22Args {
  @ApiProperty({
    required: true,
    type: () => Operatore22CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore22CreateInput)
  @Field(() => Operatore22CreateInput, { nullable: false })
  data!: Operatore22CreateInput;
}

export { CreateOperatore22Args as CreateOperatore22Args };
