/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore22WhereInput } from "./Operatore22WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore22OrderByInput } from "./Operatore22OrderByInput";

@ArgsType()
class Operatore22FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore22WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore22WhereInput, { nullable: true })
  @Type(() => Operatore22WhereInput)
  where?: Operatore22WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore22OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore22OrderByInput], { nullable: true })
  @Type(() => Operatore22OrderByInput)
  orderBy?: Array<Operatore22OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore22FindManyArgs as Operatore22FindManyArgs };
