/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore22WhereInput } from "./Operatore22WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore22ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore22WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore22WhereInput)
  @IsOptional()
  @Field(() => Operatore22WhereInput, {
    nullable: true,
  })
  every?: Operatore22WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore22WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore22WhereInput)
  @IsOptional()
  @Field(() => Operatore22WhereInput, {
    nullable: true,
  })
  some?: Operatore22WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore22WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore22WhereInput)
  @IsOptional()
  @Field(() => Operatore22WhereInput, {
    nullable: true,
  })
  none?: Operatore22WhereInput;
}
export { Operatore22ListRelationFilter as Operatore22ListRelationFilter };
