/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore27CreateInput } from "./Operatore27CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore27Args {
  @ApiProperty({
    required: true,
    type: () => Operatore27CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore27CreateInput)
  @Field(() => Operatore27CreateInput, { nullable: false })
  data!: Operatore27CreateInput;
}

export { CreateOperatore27Args as CreateOperatore27Args };
