/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore27WhereUniqueInput } from "./Operatore27WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteOperatore27Args {
  @ApiProperty({
    required: true,
    type: () => Operatore27WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore27WhereUniqueInput)
  @Field(() => Operatore27WhereUniqueInput, { nullable: false })
  where!: Operatore27WhereUniqueInput;
}

export { DeleteOperatore27Args as DeleteOperatore27Args };
