/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore27WhereInput } from "./Operatore27WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore27OrderByInput } from "./Operatore27OrderByInput";

@ArgsType()
class Operatore27FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore27WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore27WhereInput, { nullable: true })
  @Type(() => Operatore27WhereInput)
  where?: Operatore27WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore27OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore27OrderByInput], { nullable: true })
  @Type(() => Operatore27OrderByInput)
  orderBy?: Array<Operatore27OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore27FindManyArgs as Operatore27FindManyArgs };
