/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore27WhereInput } from "./Operatore27WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore27CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore27WhereInput,
  })
  @Field(() => Operatore27WhereInput, { nullable: true })
  @Type(() => Operatore27WhereInput)
  where?: Operatore27WhereInput;
}

export { Operatore27CountArgs as Operatore27CountArgs };
