/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore13CreateInput } from "./Operatore13CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore13Args {
  @ApiProperty({
    required: true,
    type: () => Operatore13CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore13CreateInput)
  @Field(() => Operatore13CreateInput, { nullable: false })
  data!: Operatore13CreateInput;
}

export { CreateOperatore13Args as CreateOperatore13Args };
