/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore13WhereInput } from "./Operatore13WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore13ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore13WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore13WhereInput)
  @IsOptional()
  @Field(() => Operatore13WhereInput, {
    nullable: true,
  })
  every?: Operatore13WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore13WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore13WhereInput)
  @IsOptional()
  @Field(() => Operatore13WhereInput, {
    nullable: true,
  })
  some?: Operatore13WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore13WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore13WhereInput)
  @IsOptional()
  @Field(() => Operatore13WhereInput, {
    nullable: true,
  })
  none?: Operatore13WhereInput;
}
export { Operatore13ListRelationFilter as Operatore13ListRelationFilter };
