/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore13WhereInput } from "./Operatore13WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore13OrderByInput } from "./Operatore13OrderByInput";

@ArgsType()
class Operatore13FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore13WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore13WhereInput, { nullable: true })
  @Type(() => Operatore13WhereInput)
  where?: Operatore13WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore13OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore13OrderByInput], { nullable: true })
  @Type(() => Operatore13OrderByInput)
  orderBy?: Array<Operatore13OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore13FindManyArgs as Operatore13FindManyArgs };
