/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore13WhereUniqueInput } from "./Operatore13WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore13UpdateInput } from "./Operatore13UpdateInput";

@ArgsType()
class UpdateOperatore13Args {
  @ApiProperty({
    required: true,
    type: () => Operatore13WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore13WhereUniqueInput)
  @Field(() => Operatore13WhereUniqueInput, { nullable: false })
  where!: Operatore13WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore13UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore13UpdateInput)
  @Field(() => Operatore13UpdateInput, { nullable: false })
  data!: Operatore13UpdateInput;
}

export { UpdateOperatore13Args as UpdateOperatore13Args };
