/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore6Service } from "../operatore6.service";
import { Operatore6CreateInput } from "./Operatore6CreateInput";
import { Operatore6 } from "./Operatore6";
import { Operatore6FindManyArgs } from "./Operatore6FindManyArgs";
import { Operatore6WhereUniqueInput } from "./Operatore6WhereUniqueInput";
import { Operatore6UpdateInput } from "./Operatore6UpdateInput";

export class Operatore6ControllerBase {
  constructor(protected readonly service: Operatore6Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore6 })
  async createOperatore6(
    @common.Body() data: Operatore6CreateInput
  ): Promise<Operatore6> {
    return await this.service.createOperatore6({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore6] })
  @ApiNestedQuery(Operatore6FindManyArgs)
  async operatore6s(@common.Req() request: Request): Promise<Operatore6[]> {
    const args = plainToClass(Operatore6FindManyArgs, request.query);
    return this.service.operatore6s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore6 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore6(
    @common.Param() params: Operatore6WhereUniqueInput
  ): Promise<Operatore6 | null> {
    const result = await this.service.operatore6({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore6 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore6(
    @common.Param() params: Operatore6WhereUniqueInput,
    @common.Body() data: Operatore6UpdateInput
  ): Promise<Operatore6 | null> {
    try {
      return await this.service.updateOperatore6({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore6 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore6(
    @common.Param() params: Operatore6WhereUniqueInput
  ): Promise<Operatore6 | null> {
    try {
      return await this.service.deleteOperatore6({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
