/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore6WhereInput } from "./Operatore6WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore6OrderByInput } from "./Operatore6OrderByInput";

@ArgsType()
class Operatore6FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore6WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore6WhereInput, { nullable: true })
  @Type(() => Operatore6WhereInput)
  where?: Operatore6WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore6OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore6OrderByInput], { nullable: true })
  @Type(() => Operatore6OrderByInput)
  orderBy?: Array<Operatore6OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore6FindManyArgs as Operatore6FindManyArgs };
