/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore6WhereInput } from "./Operatore6WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore6ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore6WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore6WhereInput)
  @IsOptional()
  @Field(() => Operatore6WhereInput, {
    nullable: true,
  })
  every?: Operatore6WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore6WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore6WhereInput)
  @IsOptional()
  @Field(() => Operatore6WhereInput, {
    nullable: true,
  })
  some?: Operatore6WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore6WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore6WhereInput)
  @IsOptional()
  @Field(() => Operatore6WhereInput, {
    nullable: true,
  })
  none?: Operatore6WhereInput;
}
export { Operatore6ListRelationFilter as Operatore6ListRelationFilter };
