/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore21WhereInput } from "./Operatore21WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore21CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore21WhereInput,
  })
  @Field(() => Operatore21WhereInput, { nullable: true })
  @Type(() => Operatore21WhereInput)
  where?: Operatore21WhereInput;
}

export { Operatore21CountArgs as Operatore21CountArgs };
