/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore21Service } from "../operatore21.service";
import { Operatore21CreateInput } from "./Operatore21CreateInput";
import { Operatore21 } from "./Operatore21";
import { Operatore21FindManyArgs } from "./Operatore21FindManyArgs";
import { Operatore21WhereUniqueInput } from "./Operatore21WhereUniqueInput";
import { Operatore21UpdateInput } from "./Operatore21UpdateInput";

export class Operatore21ControllerBase {
  constructor(protected readonly service: Operatore21Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore21 })
  async createOperatore21(
    @common.Body() data: Operatore21CreateInput
  ): Promise<Operatore21> {
    return await this.service.createOperatore21({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore21] })
  @ApiNestedQuery(Operatore21FindManyArgs)
  async operatore21s(@common.Req() request: Request): Promise<Operatore21[]> {
    const args = plainToClass(Operatore21FindManyArgs, request.query);
    return this.service.operatore21s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore21 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore21(
    @common.Param() params: Operatore21WhereUniqueInput
  ): Promise<Operatore21 | null> {
    const result = await this.service.operatore21({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore21 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore21(
    @common.Param() params: Operatore21WhereUniqueInput,
    @common.Body() data: Operatore21UpdateInput
  ): Promise<Operatore21 | null> {
    try {
      return await this.service.updateOperatore21({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore21 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore21(
    @common.Param() params: Operatore21WhereUniqueInput
  ): Promise<Operatore21 | null> {
    try {
      return await this.service.deleteOperatore21({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
