/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore21WhereInput } from "./Operatore21WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore21OrderByInput } from "./Operatore21OrderByInput";

@ArgsType()
class Operatore21FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore21WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore21WhereInput, { nullable: true })
  @Type(() => Operatore21WhereInput)
  where?: Operatore21WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore21OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore21OrderByInput], { nullable: true })
  @Type(() => Operatore21OrderByInput)
  orderBy?: Array<Operatore21OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore21FindManyArgs as Operatore21FindManyArgs };
