/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore21WhereUniqueInput } from "./Operatore21WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class Operatore21FindUniqueArgs {
  @ApiProperty({
    required: true,
    type: () => Operatore21WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore21WhereUniqueInput)
  @Field(() => Operatore21WhereUniqueInput, { nullable: false })
  where!: Operatore21WhereUniqueInput;
}

export { Operatore21FindUniqueArgs as Operatore21FindUniqueArgs };
