/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore21WhereInput } from "./Operatore21WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore21ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore21WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore21WhereInput)
  @IsOptional()
  @Field(() => Operatore21WhereInput, {
    nullable: true,
  })
  every?: Operatore21WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore21WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore21WhereInput)
  @IsOptional()
  @Field(() => Operatore21WhereInput, {
    nullable: true,
  })
  some?: Operatore21WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore21WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore21WhereInput)
  @IsOptional()
  @Field(() => Operatore21WhereInput, {
    nullable: true,
  })
  none?: Operatore21WhereInput;
}
export { Operatore21ListRelationFilter as Operatore21ListRelationFilter };
