/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore21WhereUniqueInput } from "./Operatore21WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore21UpdateInput } from "./Operatore21UpdateInput";

@ArgsType()
class UpdateOperatore21Args {
  @ApiProperty({
    required: true,
    type: () => Operatore21WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore21WhereUniqueInput)
  @Field(() => Operatore21WhereUniqueInput, { nullable: false })
  where!: Operatore21WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore21UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore21UpdateInput)
  @Field(() => Operatore21UpdateInput, { nullable: false })
  data!: Operatore21UpdateInput;
}

export { UpdateOperatore21Args as UpdateOperatore21Args };
