/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore4CreateInput } from "./Operatore4CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore4Args {
  @ApiProperty({
    required: true,
    type: () => Operatore4CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore4CreateInput)
  @Field(() => Operatore4CreateInput, { nullable: false })
  data!: Operatore4CreateInput;
}

export { CreateOperatore4Args as CreateOperatore4Args };
