/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore4Service } from "../operatore4.service";
import { Operatore4CreateInput } from "./Operatore4CreateInput";
import { Operatore4 } from "./Operatore4";
import { Operatore4FindManyArgs } from "./Operatore4FindManyArgs";
import { Operatore4WhereUniqueInput } from "./Operatore4WhereUniqueInput";
import { Operatore4UpdateInput } from "./Operatore4UpdateInput";

export class Operatore4ControllerBase {
  constructor(protected readonly service: Operatore4Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore4 })
  async createOperatore4(
    @common.Body() data: Operatore4CreateInput
  ): Promise<Operatore4> {
    return await this.service.createOperatore4({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore4] })
  @ApiNestedQuery(Operatore4FindManyArgs)
  async operatore4s(@common.Req() request: Request): Promise<Operatore4[]> {
    const args = plainToClass(Operatore4FindManyArgs, request.query);
    return this.service.operatore4s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore4 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore4(
    @common.Param() params: Operatore4WhereUniqueInput
  ): Promise<Operatore4 | null> {
    const result = await this.service.operatore4({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore4 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore4(
    @common.Param() params: Operatore4WhereUniqueInput,
    @common.Body() data: Operatore4UpdateInput
  ): Promise<Operatore4 | null> {
    try {
      return await this.service.updateOperatore4({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore4 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore4(
    @common.Param() params: Operatore4WhereUniqueInput
  ): Promise<Operatore4 | null> {
    try {
      return await this.service.deleteOperatore4({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
