/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore4WhereInput } from "./Operatore4WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore4OrderByInput } from "./Operatore4OrderByInput";

@ArgsType()
class Operatore4FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore4WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore4WhereInput, { nullable: true })
  @Type(() => Operatore4WhereInput)
  where?: Operatore4WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore4OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore4OrderByInput], { nullable: true })
  @Type(() => Operatore4OrderByInput)
  orderBy?: Array<Operatore4OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore4FindManyArgs as Operatore4FindManyArgs };
