/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore4WhereUniqueInput } from "./Operatore4WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore4UpdateInput } from "./Operatore4UpdateInput";

@ArgsType()
class UpdateOperatore4Args {
  @ApiProperty({
    required: true,
    type: () => Operatore4WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore4WhereUniqueInput)
  @Field(() => Operatore4WhereUniqueInput, { nullable: false })
  where!: Operatore4WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore4UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore4UpdateInput)
  @Field(() => Operatore4UpdateInput, { nullable: false })
  data!: Operatore4UpdateInput;
}

export { UpdateOperatore4Args as UpdateOperatore4Args };
