/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore15WhereInput } from "./Operatore15WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore15CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore15WhereInput,
  })
  @Field(() => Operatore15WhereInput, { nullable: true })
  @Type(() => Operatore15WhereInput)
  where?: Operatore15WhereInput;
}

export { Operatore15CountArgs as Operatore15CountArgs };
