/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore15Service } from "../operatore15.service";
import { Operatore15CreateInput } from "./Operatore15CreateInput";
import { Operatore15 } from "./Operatore15";
import { Operatore15FindManyArgs } from "./Operatore15FindManyArgs";
import { Operatore15WhereUniqueInput } from "./Operatore15WhereUniqueInput";
import { Operatore15UpdateInput } from "./Operatore15UpdateInput";

export class Operatore15ControllerBase {
  constructor(protected readonly service: Operatore15Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore15 })
  async createOperatore15(
    @common.Body() data: Operatore15CreateInput
  ): Promise<Operatore15> {
    return await this.service.createOperatore15({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore15] })
  @ApiNestedQuery(Operatore15FindManyArgs)
  async operatore15s(@common.Req() request: Request): Promise<Operatore15[]> {
    const args = plainToClass(Operatore15FindManyArgs, request.query);
    return this.service.operatore15s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore15 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore15(
    @common.Param() params: Operatore15WhereUniqueInput
  ): Promise<Operatore15 | null> {
    const result = await this.service.operatore15({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore15 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore15(
    @common.Param() params: Operatore15WhereUniqueInput,
    @common.Body() data: Operatore15UpdateInput
  ): Promise<Operatore15 | null> {
    try {
      return await this.service.updateOperatore15({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore15 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore15(
    @common.Param() params: Operatore15WhereUniqueInput
  ): Promise<Operatore15 | null> {
    try {
      return await this.service.deleteOperatore15({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
