/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore15WhereInput } from "./Operatore15WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore15ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore15WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore15WhereInput)
  @IsOptional()
  @Field(() => Operatore15WhereInput, {
    nullable: true,
  })
  every?: Operatore15WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore15WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore15WhereInput)
  @IsOptional()
  @Field(() => Operatore15WhereInput, {
    nullable: true,
  })
  some?: Operatore15WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore15WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore15WhereInput)
  @IsOptional()
  @Field(() => Operatore15WhereInput, {
    nullable: true,
  })
  none?: Operatore15WhereInput;
}
export { Operatore15ListRelationFilter as Operatore15ListRelationFilter };
