/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore15WhereInput } from "./Operatore15WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore15OrderByInput } from "./Operatore15OrderByInput";

@ArgsType()
class Operatore15FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore15WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore15WhereInput, { nullable: true })
  @Type(() => Operatore15WhereInput)
  where?: Operatore15WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore15OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore15OrderByInput], { nullable: true })
  @Type(() => Operatore15OrderByInput)
  orderBy?: Array<Operatore15OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore15FindManyArgs as Operatore15FindManyArgs };
