/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore15WhereUniqueInput } from "./Operatore15WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore15UpdateInput } from "./Operatore15UpdateInput";

@ArgsType()
class UpdateOperatore15Args {
  @ApiProperty({
    required: true,
    type: () => Operatore15WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore15WhereUniqueInput)
  @Field(() => Operatore15WhereUniqueInput, { nullable: false })
  where!: Operatore15WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore15UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore15UpdateInput)
  @Field(() => Operatore15UpdateInput, { nullable: false })
  data!: Operatore15UpdateInput;
}

export { UpdateOperatore15Args as UpdateOperatore15Args };
