/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore20WhereUniqueInput } from "./Operatore20WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteOperatore20Args {
  @ApiProperty({
    required: true,
    type: () => Operatore20WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore20WhereUniqueInput)
  @Field(() => Operatore20WhereUniqueInput, { nullable: false })
  where!: Operatore20WhereUniqueInput;
}

export { DeleteOperatore20Args as DeleteOperatore20Args };
