/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore20Service } from "../operatore20.service";
import { Operatore20CreateInput } from "./Operatore20CreateInput";
import { Operatore20 } from "./Operatore20";
import { Operatore20FindManyArgs } from "./Operatore20FindManyArgs";
import { Operatore20WhereUniqueInput } from "./Operatore20WhereUniqueInput";
import { Operatore20UpdateInput } from "./Operatore20UpdateInput";

export class Operatore20ControllerBase {
  constructor(protected readonly service: Operatore20Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore20 })
  async createOperatore20(
    @common.Body() data: Operatore20CreateInput
  ): Promise<Operatore20> {
    return await this.service.createOperatore20({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore20] })
  @ApiNestedQuery(Operatore20FindManyArgs)
  async operatore20s(@common.Req() request: Request): Promise<Operatore20[]> {
    const args = plainToClass(Operatore20FindManyArgs, request.query);
    return this.service.operatore20s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore20 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore20(
    @common.Param() params: Operatore20WhereUniqueInput
  ): Promise<Operatore20 | null> {
    const result = await this.service.operatore20({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore20 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore20(
    @common.Param() params: Operatore20WhereUniqueInput,
    @common.Body() data: Operatore20UpdateInput
  ): Promise<Operatore20 | null> {
    try {
      return await this.service.updateOperatore20({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore20 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore20(
    @common.Param() params: Operatore20WhereUniqueInput
  ): Promise<Operatore20 | null> {
    try {
      return await this.service.deleteOperatore20({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
