/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore26CreateInput } from "./Operatore26CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore26Args {
  @ApiProperty({
    required: true,
    type: () => Operatore26CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore26CreateInput)
  @Field(() => Operatore26CreateInput, { nullable: false })
  data!: Operatore26CreateInput;
}

export { CreateOperatore26Args as CreateOperatore26Args };
