/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore26WhereInput } from "./Operatore26WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore26OrderByInput } from "./Operatore26OrderByInput";

@ArgsType()
class Operatore26FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore26WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore26WhereInput, { nullable: true })
  @Type(() => Operatore26WhereInput)
  where?: Operatore26WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore26OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore26OrderByInput], { nullable: true })
  @Type(() => Operatore26OrderByInput)
  orderBy?: Array<Operatore26OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore26FindManyArgs as Operatore26FindManyArgs };
