/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore26Service } from "../operatore26.service";
import { Operatore26CreateInput } from "./Operatore26CreateInput";
import { Operatore26 } from "./Operatore26";
import { Operatore26FindManyArgs } from "./Operatore26FindManyArgs";
import { Operatore26WhereUniqueInput } from "./Operatore26WhereUniqueInput";
import { Operatore26UpdateInput } from "./Operatore26UpdateInput";

export class Operatore26ControllerBase {
  constructor(protected readonly service: Operatore26Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore26 })
  async createOperatore26(
    @common.Body() data: Operatore26CreateInput
  ): Promise<Operatore26> {
    return await this.service.createOperatore26({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore26] })
  @ApiNestedQuery(Operatore26FindManyArgs)
  async operatore26s(@common.Req() request: Request): Promise<Operatore26[]> {
    const args = plainToClass(Operatore26FindManyArgs, request.query);
    return this.service.operatore26s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore26 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore26(
    @common.Param() params: Operatore26WhereUniqueInput
  ): Promise<Operatore26 | null> {
    const result = await this.service.operatore26({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore26 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore26(
    @common.Param() params: Operatore26WhereUniqueInput,
    @common.Body() data: Operatore26UpdateInput
  ): Promise<Operatore26 | null> {
    try {
      return await this.service.updateOperatore26({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore26 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore26(
    @common.Param() params: Operatore26WhereUniqueInput
  ): Promise<Operatore26 | null> {
    try {
      return await this.service.deleteOperatore26({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
