/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore14Service } from "../operatore14.service";
import { Operatore14CreateInput } from "./Operatore14CreateInput";
import { Operatore14 } from "./Operatore14";
import { Operatore14FindManyArgs } from "./Operatore14FindManyArgs";
import { Operatore14WhereUniqueInput } from "./Operatore14WhereUniqueInput";
import { Operatore14UpdateInput } from "./Operatore14UpdateInput";

export class Operatore14ControllerBase {
  constructor(protected readonly service: Operatore14Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore14 })
  async createOperatore14(
    @common.Body() data: Operatore14CreateInput
  ): Promise<Operatore14> {
    return await this.service.createOperatore14({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore14] })
  @ApiNestedQuery(Operatore14FindManyArgs)
  async operatore14s(@common.Req() request: Request): Promise<Operatore14[]> {
    const args = plainToClass(Operatore14FindManyArgs, request.query);
    return this.service.operatore14s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore14 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore14(
    @common.Param() params: Operatore14WhereUniqueInput
  ): Promise<Operatore14 | null> {
    const result = await this.service.operatore14({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore14 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore14(
    @common.Param() params: Operatore14WhereUniqueInput,
    @common.Body() data: Operatore14UpdateInput
  ): Promise<Operatore14 | null> {
    try {
      return await this.service.updateOperatore14({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore14 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore14(
    @common.Param() params: Operatore14WhereUniqueInput
  ): Promise<Operatore14 | null> {
    try {
      return await this.service.deleteOperatore14({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
