/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore14WhereInput } from "./Operatore14WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore14CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore14WhereInput,
  })
  @Field(() => Operatore14WhereInput, { nullable: true })
  @Type(() => Operatore14WhereInput)
  where?: Operatore14WhereInput;
}

export { Operatore14CountArgs as Operatore14CountArgs };
