/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore14WhereUniqueInput } from "./Operatore14WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore14UpdateInput } from "./Operatore14UpdateInput";

@ArgsType()
class UpdateOperatore14Args {
  @ApiProperty({
    required: true,
    type: () => Operatore14WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore14WhereUniqueInput)
  @Field(() => Operatore14WhereUniqueInput, { nullable: false })
  where!: Operatore14WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore14UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore14UpdateInput)
  @Field(() => Operatore14UpdateInput, { nullable: false })
  data!: Operatore14UpdateInput;
}

export { UpdateOperatore14Args as UpdateOperatore14Args };
