/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore10CreateInput } from "./Operatore10CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore10Args {
  @ApiProperty({
    required: true,
    type: () => Operatore10CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore10CreateInput)
  @Field(() => Operatore10CreateInput, { nullable: false })
  data!: Operatore10CreateInput;
}

export { CreateOperatore10Args as CreateOperatore10Args };
