/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore10Service } from "../operatore10.service";
import { Operatore10CreateInput } from "./Operatore10CreateInput";
import { Operatore10 } from "./Operatore10";
import { Operatore10FindManyArgs } from "./Operatore10FindManyArgs";
import { Operatore10WhereUniqueInput } from "./Operatore10WhereUniqueInput";
import { Operatore10UpdateInput } from "./Operatore10UpdateInput";

export class Operatore10ControllerBase {
  constructor(protected readonly service: Operatore10Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore10 })
  async createOperatore10(
    @common.Body() data: Operatore10CreateInput
  ): Promise<Operatore10> {
    return await this.service.createOperatore10({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore10] })
  @ApiNestedQuery(Operatore10FindManyArgs)
  async operatore10s(@common.Req() request: Request): Promise<Operatore10[]> {
    const args = plainToClass(Operatore10FindManyArgs, request.query);
    return this.service.operatore10s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore10 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore10(
    @common.Param() params: Operatore10WhereUniqueInput
  ): Promise<Operatore10 | null> {
    const result = await this.service.operatore10({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore10 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore10(
    @common.Param() params: Operatore10WhereUniqueInput,
    @common.Body() data: Operatore10UpdateInput
  ): Promise<Operatore10 | null> {
    try {
      return await this.service.updateOperatore10({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore10 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore10(
    @common.Param() params: Operatore10WhereUniqueInput
  ): Promise<Operatore10 | null> {
    try {
      return await this.service.deleteOperatore10({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
