/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore10WhereUniqueInput } from "./Operatore10WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore10UpdateInput } from "./Operatore10UpdateInput";

@ArgsType()
class UpdateOperatore10Args {
  @ApiProperty({
    required: true,
    type: () => Operatore10WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore10WhereUniqueInput)
  @Field(() => Operatore10WhereUniqueInput, { nullable: false })
  where!: Operatore10WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore10UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore10UpdateInput)
  @Field(() => Operatore10UpdateInput, { nullable: false })
  data!: Operatore10UpdateInput;
}

export { UpdateOperatore10Args as UpdateOperatore10Args };
