/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore29WhereInput } from "./Operatore29WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore29CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore29WhereInput,
  })
  @Field(() => Operatore29WhereInput, { nullable: true })
  @Type(() => Operatore29WhereInput)
  where?: Operatore29WhereInput;
}

export { Operatore29CountArgs as Operatore29CountArgs };
