/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore29Service } from "../operatore29.service";
import { Operatore29CreateInput } from "./Operatore29CreateInput";
import { Operatore29 } from "./Operatore29";
import { Operatore29FindManyArgs } from "./Operatore29FindManyArgs";
import { Operatore29WhereUniqueInput } from "./Operatore29WhereUniqueInput";
import { Operatore29UpdateInput } from "./Operatore29UpdateInput";

export class Operatore29ControllerBase {
  constructor(protected readonly service: Operatore29Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore29 })
  async createOperatore29(
    @common.Body() data: Operatore29CreateInput
  ): Promise<Operatore29> {
    return await this.service.createOperatore29({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore29] })
  @ApiNestedQuery(Operatore29FindManyArgs)
  async operatore29s(@common.Req() request: Request): Promise<Operatore29[]> {
    const args = plainToClass(Operatore29FindManyArgs, request.query);
    return this.service.operatore29s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore29 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore29(
    @common.Param() params: Operatore29WhereUniqueInput
  ): Promise<Operatore29 | null> {
    const result = await this.service.operatore29({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore29 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore29(
    @common.Param() params: Operatore29WhereUniqueInput,
    @common.Body() data: Operatore29UpdateInput
  ): Promise<Operatore29 | null> {
    try {
      return await this.service.updateOperatore29({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore29 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore29(
    @common.Param() params: Operatore29WhereUniqueInput
  ): Promise<Operatore29 | null> {
    try {
      return await this.service.deleteOperatore29({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
