/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore30CreateInput } from "./Operatore30CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore30Args {
  @ApiProperty({
    required: true,
    type: () => Operatore30CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore30CreateInput)
  @Field(() => Operatore30CreateInput, { nullable: false })
  data!: Operatore30CreateInput;
}

export { CreateOperatore30Args as CreateOperatore30Args };
