/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore30WhereUniqueInput } from "./Operatore30WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore30UpdateInput } from "./Operatore30UpdateInput";

@ArgsType()
class UpdateOperatore30Args {
  @ApiProperty({
    required: true,
    type: () => Operatore30WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore30WhereUniqueInput)
  @Field(() => Operatore30WhereUniqueInput, { nullable: false })
  where!: Operatore30WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore30UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore30UpdateInput)
  @Field(() => Operatore30UpdateInput, { nullable: false })
  data!: Operatore30UpdateInput;
}

export { UpdateOperatore30Args as UpdateOperatore30Args };
