/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore5WhereInput } from "./Operatore5WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore5ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore5WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore5WhereInput)
  @IsOptional()
  @Field(() => Operatore5WhereInput, {
    nullable: true,
  })
  every?: Operatore5WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore5WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore5WhereInput)
  @IsOptional()
  @Field(() => Operatore5WhereInput, {
    nullable: true,
  })
  some?: Operatore5WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore5WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore5WhereInput)
  @IsOptional()
  @Field(() => Operatore5WhereInput, {
    nullable: true,
  })
  none?: Operatore5WhereInput;
}
export { Operatore5ListRelationFilter as Operatore5ListRelationFilter };
