/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore5WhereInput } from "./Operatore5WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore5CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore5WhereInput,
  })
  @Field(() => Operatore5WhereInput, { nullable: true })
  @Type(() => Operatore5WhereInput)
  where?: Operatore5WhereInput;
}

export { Operatore5CountArgs as Operatore5CountArgs };
