/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore5WhereUniqueInput } from "./Operatore5WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore5UpdateInput } from "./Operatore5UpdateInput";

@ArgsType()
class UpdateOperatore5Args {
  @ApiProperty({
    required: true,
    type: () => Operatore5WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore5WhereUniqueInput)
  @Field(() => Operatore5WhereUniqueInput, { nullable: false })
  where!: Operatore5WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore5UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore5UpdateInput)
  @Field(() => Operatore5UpdateInput, { nullable: false })
  data!: Operatore5UpdateInput;
}

export { UpdateOperatore5Args as UpdateOperatore5Args };
