/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore25CreateInput } from "./Operatore25CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore25Args {
  @ApiProperty({
    required: true,
    type: () => Operatore25CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore25CreateInput)
  @Field(() => Operatore25CreateInput, { nullable: false })
  data!: Operatore25CreateInput;
}

export { CreateOperatore25Args as CreateOperatore25Args };
