/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore25WhereInput } from "./Operatore25WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore25ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore25WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore25WhereInput)
  @IsOptional()
  @Field(() => Operatore25WhereInput, {
    nullable: true,
  })
  every?: Operatore25WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore25WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore25WhereInput)
  @IsOptional()
  @Field(() => Operatore25WhereInput, {
    nullable: true,
  })
  some?: Operatore25WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore25WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore25WhereInput)
  @IsOptional()
  @Field(() => Operatore25WhereInput, {
    nullable: true,
  })
  none?: Operatore25WhereInput;
}
export { Operatore25ListRelationFilter as Operatore25ListRelationFilter };
