/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore25WhereInput } from "./Operatore25WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore25CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore25WhereInput,
  })
  @Field(() => Operatore25WhereInput, { nullable: true })
  @Type(() => Operatore25WhereInput)
  where?: Operatore25WhereInput;
}

export { Operatore25CountArgs as Operatore25CountArgs };
