/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore7WhereInput } from "./Operatore7WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore7CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore7WhereInput,
  })
  @Field(() => Operatore7WhereInput, { nullable: true })
  @Type(() => Operatore7WhereInput)
  where?: Operatore7WhereInput;
}

export { Operatore7CountArgs as Operatore7CountArgs };
