/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore7WhereInput } from "./Operatore7WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore7OrderByInput } from "./Operatore7OrderByInput";

@ArgsType()
class Operatore7FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore7WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore7WhereInput, { nullable: true })
  @Type(() => Operatore7WhereInput)
  where?: Operatore7WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore7OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore7OrderByInput], { nullable: true })
  @Type(() => Operatore7OrderByInput)
  orderBy?: Array<Operatore7OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore7FindManyArgs as Operatore7FindManyArgs };
