/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore11WhereInput } from "./Operatore11WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore11OrderByInput } from "./Operatore11OrderByInput";

@ArgsType()
class Operatore11FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore11WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore11WhereInput, { nullable: true })
  @Type(() => Operatore11WhereInput)
  where?: Operatore11WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore11OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore11OrderByInput], { nullable: true })
  @Type(() => Operatore11OrderByInput)
  orderBy?: Array<Operatore11OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore11FindManyArgs as Operatore11FindManyArgs };
