/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore11Service } from "../operatore11.service";
import { Operatore11CreateInput } from "./Operatore11CreateInput";
import { Operatore11 } from "./Operatore11";
import { Operatore11FindManyArgs } from "./Operatore11FindManyArgs";
import { Operatore11WhereUniqueInput } from "./Operatore11WhereUniqueInput";
import { Operatore11UpdateInput } from "./Operatore11UpdateInput";

export class Operatore11ControllerBase {
  constructor(protected readonly service: Operatore11Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore11 })
  async createOperatore11(
    @common.Body() data: Operatore11CreateInput
  ): Promise<Operatore11> {
    return await this.service.createOperatore11({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore11] })
  @ApiNestedQuery(Operatore11FindManyArgs)
  async operatore11s(@common.Req() request: Request): Promise<Operatore11[]> {
    const args = plainToClass(Operatore11FindManyArgs, request.query);
    return this.service.operatore11s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore11 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore11(
    @common.Param() params: Operatore11WhereUniqueInput
  ): Promise<Operatore11 | null> {
    const result = await this.service.operatore11({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore11 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore11(
    @common.Param() params: Operatore11WhereUniqueInput,
    @common.Body() data: Operatore11UpdateInput
  ): Promise<Operatore11 | null> {
    try {
      return await this.service.updateOperatore11({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore11 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore11(
    @common.Param() params: Operatore11WhereUniqueInput
  ): Promise<Operatore11 | null> {
    try {
      return await this.service.deleteOperatore11({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
