/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore11WhereInput } from "./Operatore11WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore11CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore11WhereInput,
  })
  @Field(() => Operatore11WhereInput, { nullable: true })
  @Type(() => Operatore11WhereInput)
  where?: Operatore11WhereInput;
}

export { Operatore11CountArgs as Operatore11CountArgs };
