/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore19WhereInput } from "./Operatore19WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore19OrderByInput } from "./Operatore19OrderByInput";

@ArgsType()
class Operatore19FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore19WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore19WhereInput, { nullable: true })
  @Type(() => Operatore19WhereInput)
  where?: Operatore19WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore19OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore19OrderByInput], { nullable: true })
  @Type(() => Operatore19OrderByInput)
  orderBy?: Array<Operatore19OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore19FindManyArgs as Operatore19FindManyArgs };
