/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore19Service } from "../operatore19.service";
import { Operatore19CreateInput } from "./Operatore19CreateInput";
import { Operatore19 } from "./Operatore19";
import { Operatore19FindManyArgs } from "./Operatore19FindManyArgs";
import { Operatore19WhereUniqueInput } from "./Operatore19WhereUniqueInput";
import { Operatore19UpdateInput } from "./Operatore19UpdateInput";

export class Operatore19ControllerBase {
  constructor(protected readonly service: Operatore19Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore19 })
  async createOperatore19(
    @common.Body() data: Operatore19CreateInput
  ): Promise<Operatore19> {
    return await this.service.createOperatore19({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore19] })
  @ApiNestedQuery(Operatore19FindManyArgs)
  async operatore19s(@common.Req() request: Request): Promise<Operatore19[]> {
    const args = plainToClass(Operatore19FindManyArgs, request.query);
    return this.service.operatore19s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore19 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore19(
    @common.Param() params: Operatore19WhereUniqueInput
  ): Promise<Operatore19 | null> {
    const result = await this.service.operatore19({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore19 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore19(
    @common.Param() params: Operatore19WhereUniqueInput,
    @common.Body() data: Operatore19UpdateInput
  ): Promise<Operatore19 | null> {
    try {
      return await this.service.updateOperatore19({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore19 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore19(
    @common.Param() params: Operatore19WhereUniqueInput
  ): Promise<Operatore19 | null> {
    try {
      return await this.service.deleteOperatore19({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
