/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore19WhereInput } from "./Operatore19WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore19CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore19WhereInput,
  })
  @Field(() => Operatore19WhereInput, { nullable: true })
  @Type(() => Operatore19WhereInput)
  where?: Operatore19WhereInput;
}

export { Operatore19CountArgs as Operatore19CountArgs };
