/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore24WhereUniqueInput } from "./Operatore24WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteOperatore24Args {
  @ApiProperty({
    required: true,
    type: () => Operatore24WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore24WhereUniqueInput)
  @Field(() => Operatore24WhereUniqueInput, { nullable: false })
  where!: Operatore24WhereUniqueInput;
}

export { DeleteOperatore24Args as DeleteOperatore24Args };
