/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore24Service } from "../operatore24.service";
import { Operatore24CreateInput } from "./Operatore24CreateInput";
import { Operatore24 } from "./Operatore24";
import { Operatore24FindManyArgs } from "./Operatore24FindManyArgs";
import { Operatore24WhereUniqueInput } from "./Operatore24WhereUniqueInput";
import { Operatore24UpdateInput } from "./Operatore24UpdateInput";

export class Operatore24ControllerBase {
  constructor(protected readonly service: Operatore24Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore24 })
  async createOperatore24(
    @common.Body() data: Operatore24CreateInput
  ): Promise<Operatore24> {
    return await this.service.createOperatore24({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore24] })
  @ApiNestedQuery(Operatore24FindManyArgs)
  async operatore24s(@common.Req() request: Request): Promise<Operatore24[]> {
    const args = plainToClass(Operatore24FindManyArgs, request.query);
    return this.service.operatore24s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore24 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore24(
    @common.Param() params: Operatore24WhereUniqueInput
  ): Promise<Operatore24 | null> {
    const result = await this.service.operatore24({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore24 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore24(
    @common.Param() params: Operatore24WhereUniqueInput,
    @common.Body() data: Operatore24UpdateInput
  ): Promise<Operatore24 | null> {
    try {
      return await this.service.updateOperatore24({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore24 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore24(
    @common.Param() params: Operatore24WhereUniqueInput
  ): Promise<Operatore24 | null> {
    try {
      return await this.service.deleteOperatore24({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
