/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore24WhereInput } from "./Operatore24WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore24OrderByInput } from "./Operatore24OrderByInput";

@ArgsType()
class Operatore24FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore24WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore24WhereInput, { nullable: true })
  @Type(() => Operatore24WhereInput)
  where?: Operatore24WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore24OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore24OrderByInput], { nullable: true })
  @Type(() => Operatore24OrderByInput)
  orderBy?: Array<Operatore24OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore24FindManyArgs as Operatore24FindManyArgs };
