/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore28WhereInput } from "./Operatore28WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore28OrderByInput } from "./Operatore28OrderByInput";

@ArgsType()
class Operatore28FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore28WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore28WhereInput, { nullable: true })
  @Type(() => Operatore28WhereInput)
  where?: Operatore28WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore28OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore28OrderByInput], { nullable: true })
  @Type(() => Operatore28OrderByInput)
  orderBy?: Array<Operatore28OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore28FindManyArgs as Operatore28FindManyArgs };
