/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore28Service } from "../operatore28.service";
import { Operatore28CreateInput } from "./Operatore28CreateInput";
import { Operatore28 } from "./Operatore28";
import { Operatore28FindManyArgs } from "./Operatore28FindManyArgs";
import { Operatore28WhereUniqueInput } from "./Operatore28WhereUniqueInput";
import { Operatore28UpdateInput } from "./Operatore28UpdateInput";

export class Operatore28ControllerBase {
  constructor(protected readonly service: Operatore28Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore28 })
  async createOperatore28(
    @common.Body() data: Operatore28CreateInput
  ): Promise<Operatore28> {
    return await this.service.createOperatore28({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore28] })
  @ApiNestedQuery(Operatore28FindManyArgs)
  async operatore28s(@common.Req() request: Request): Promise<Operatore28[]> {
    const args = plainToClass(Operatore28FindManyArgs, request.query);
    return this.service.operatore28s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore28 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore28(
    @common.Param() params: Operatore28WhereUniqueInput
  ): Promise<Operatore28 | null> {
    const result = await this.service.operatore28({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore28 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore28(
    @common.Param() params: Operatore28WhereUniqueInput,
    @common.Body() data: Operatore28UpdateInput
  ): Promise<Operatore28 | null> {
    try {
      return await this.service.updateOperatore28({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore28 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore28(
    @common.Param() params: Operatore28WhereUniqueInput
  ): Promise<Operatore28 | null> {
    try {
      return await this.service.deleteOperatore28({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
