/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore28WhereInput } from "./Operatore28WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore28ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore28WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore28WhereInput)
  @IsOptional()
  @Field(() => Operatore28WhereInput, {
    nullable: true,
  })
  every?: Operatore28WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore28WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore28WhereInput)
  @IsOptional()
  @Field(() => Operatore28WhereInput, {
    nullable: true,
  })
  some?: Operatore28WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore28WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore28WhereInput)
  @IsOptional()
  @Field(() => Operatore28WhereInput, {
    nullable: true,
  })
  none?: Operatore28WhereInput;
}
export { Operatore28ListRelationFilter as Operatore28ListRelationFilter };
