/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore28WhereUniqueInput } from "./Operatore28WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore28UpdateInput } from "./Operatore28UpdateInput";

@ArgsType()
class UpdateOperatore28Args {
  @ApiProperty({
    required: true,
    type: () => Operatore28WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore28WhereUniqueInput)
  @Field(() => Operatore28WhereUniqueInput, { nullable: false })
  where!: Operatore28WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore28UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore28UpdateInput)
  @Field(() => Operatore28UpdateInput, { nullable: false })
  data!: Operatore28UpdateInput;
}

export { UpdateOperatore28Args as UpdateOperatore28Args };
