/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore9CreateInput } from "./Operatore9CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore9Args {
  @ApiProperty({
    required: true,
    type: () => Operatore9CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore9CreateInput)
  @Field(() => Operatore9CreateInput, { nullable: false })
  data!: Operatore9CreateInput;
}

export { CreateOperatore9Args as CreateOperatore9Args };
