/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore9WhereInput } from "./Operatore9WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore9ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore9WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore9WhereInput)
  @IsOptional()
  @Field(() => Operatore9WhereInput, {
    nullable: true,
  })
  every?: Operatore9WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore9WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore9WhereInput)
  @IsOptional()
  @Field(() => Operatore9WhereInput, {
    nullable: true,
  })
  some?: Operatore9WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore9WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore9WhereInput)
  @IsOptional()
  @Field(() => Operatore9WhereInput, {
    nullable: true,
  })
  none?: Operatore9WhereInput;
}
export { Operatore9ListRelationFilter as Operatore9ListRelationFilter };
