/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore9WhereInput } from "./Operatore9WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore9OrderByInput } from "./Operatore9OrderByInput";

@ArgsType()
class Operatore9FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore9WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore9WhereInput, { nullable: true })
  @Type(() => Operatore9WhereInput)
  where?: Operatore9WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore9OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore9OrderByInput], { nullable: true })
  @Type(() => Operatore9OrderByInput)
  orderBy?: Array<Operatore9OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore9FindManyArgs as Operatore9FindManyArgs };
