/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore9WhereUniqueInput } from "./Operatore9WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore9UpdateInput } from "./Operatore9UpdateInput";

@ArgsType()
class UpdateOperatore9Args {
  @ApiProperty({
    required: true,
    type: () => Operatore9WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore9WhereUniqueInput)
  @Field(() => Operatore9WhereUniqueInput, { nullable: false })
  where!: Operatore9WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore9UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore9UpdateInput)
  @Field(() => Operatore9UpdateInput, { nullable: false })
  data!: Operatore9UpdateInput;
}

export { UpdateOperatore9Args as UpdateOperatore9Args };
