/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore18Service } from "../operatore18.service";
import { Operatore18CreateInput } from "./Operatore18CreateInput";
import { Operatore18 } from "./Operatore18";
import { Operatore18FindManyArgs } from "./Operatore18FindManyArgs";
import { Operatore18WhereUniqueInput } from "./Operatore18WhereUniqueInput";
import { Operatore18UpdateInput } from "./Operatore18UpdateInput";

export class Operatore18ControllerBase {
  constructor(protected readonly service: Operatore18Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore18 })
  async createOperatore18(
    @common.Body() data: Operatore18CreateInput
  ): Promise<Operatore18> {
    return await this.service.createOperatore18({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore18] })
  @ApiNestedQuery(Operatore18FindManyArgs)
  async operatore18s(@common.Req() request: Request): Promise<Operatore18[]> {
    const args = plainToClass(Operatore18FindManyArgs, request.query);
    return this.service.operatore18s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore18 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore18(
    @common.Param() params: Operatore18WhereUniqueInput
  ): Promise<Operatore18 | null> {
    const result = await this.service.operatore18({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore18 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore18(
    @common.Param() params: Operatore18WhereUniqueInput,
    @common.Body() data: Operatore18UpdateInput
  ): Promise<Operatore18 | null> {
    try {
      return await this.service.updateOperatore18({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore18 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore18(
    @common.Param() params: Operatore18WhereUniqueInput
  ): Promise<Operatore18 | null> {
    try {
      return await this.service.deleteOperatore18({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
