/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore18WhereInput } from "./Operatore18WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore18CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore18WhereInput,
  })
  @Field(() => Operatore18WhereInput, { nullable: true })
  @Type(() => Operatore18WhereInput)
  where?: Operatore18WhereInput;
}

export { Operatore18CountArgs as Operatore18CountArgs };
