/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore18WhereUniqueInput } from "./Operatore18WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore18UpdateInput } from "./Operatore18UpdateInput";

@ArgsType()
class UpdateOperatore18Args {
  @ApiProperty({
    required: true,
    type: () => Operatore18WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore18WhereUniqueInput)
  @Field(() => Operatore18WhereUniqueInput, { nullable: false })
  where!: Operatore18WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore18UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore18UpdateInput)
  @Field(() => Operatore18UpdateInput, { nullable: false })
  data!: Operatore18UpdateInput;
}

export { UpdateOperatore18Args as UpdateOperatore18Args };
