/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore3CreateInput } from "./Operatore3CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore3Args {
  @ApiProperty({
    required: true,
    type: () => Operatore3CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore3CreateInput)
  @Field(() => Operatore3CreateInput, { nullable: false })
  data!: Operatore3CreateInput;
}

export { CreateOperatore3Args as CreateOperatore3Args };
