/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore3Service } from "../operatore3.service";
import { Operatore3CreateInput } from "./Operatore3CreateInput";
import { Operatore3 } from "./Operatore3";
import { Operatore3FindManyArgs } from "./Operatore3FindManyArgs";
import { Operatore3WhereUniqueInput } from "./Operatore3WhereUniqueInput";
import { Operatore3UpdateInput } from "./Operatore3UpdateInput";

export class Operatore3ControllerBase {
  constructor(protected readonly service: Operatore3Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore3 })
  async createOperatore3(
    @common.Body() data: Operatore3CreateInput
  ): Promise<Operatore3> {
    return await this.service.createOperatore3({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore3] })
  @ApiNestedQuery(Operatore3FindManyArgs)
  async operatore3s(@common.Req() request: Request): Promise<Operatore3[]> {
    const args = plainToClass(Operatore3FindManyArgs, request.query);
    return this.service.operatore3s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore3 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore3(
    @common.Param() params: Operatore3WhereUniqueInput
  ): Promise<Operatore3 | null> {
    const result = await this.service.operatore3({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        permessiSpeciali: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore3 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore3(
    @common.Param() params: Operatore3WhereUniqueInput,
    @common.Body() data: Operatore3UpdateInput
  ): Promise<Operatore3 | null> {
    try {
      return await this.service.updateOperatore3({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore3 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore3(
    @common.Param() params: Operatore3WhereUniqueInput
  ): Promise<Operatore3 | null> {
    try {
      return await this.service.deleteOperatore3({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          permessiSpeciali: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
