/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore3WhereInput } from "./Operatore3WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Operatore3OrderByInput } from "./Operatore3OrderByInput";

@ArgsType()
class Operatore3FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore3WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Operatore3WhereInput, { nullable: true })
  @Type(() => Operatore3WhereInput)
  where?: Operatore3WhereInput;

  @ApiProperty({
    required: false,
    type: [Operatore3OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Operatore3OrderByInput], { nullable: true })
  @Type(() => Operatore3OrderByInput)
  orderBy?: Array<Operatore3OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Operatore3FindManyArgs as Operatore3FindManyArgs };
