/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore3WhereInput } from "./Operatore3WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore3CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore3WhereInput,
  })
  @Field(() => Operatore3WhereInput, { nullable: true })
  @Type(() => Operatore3WhereInput)
  where?: Operatore3WhereInput;
}

export { Operatore3CountArgs as Operatore3CountArgs };
