/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore3WhereUniqueInput } from "./Operatore3WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Operatore3UpdateInput } from "./Operatore3UpdateInput";

@ArgsType()
class UpdateOperatore3Args {
  @ApiProperty({
    required: true,
    type: () => Operatore3WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore3WhereUniqueInput)
  @Field(() => Operatore3WhereUniqueInput, { nullable: false })
  where!: Operatore3WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => Operatore3UpdateInput,
  })
  @ValidateNested()
  @Type(() => Operatore3UpdateInput)
  @Field(() => Operatore3UpdateInput, { nullable: false })
  data!: Operatore3UpdateInput;
}

export { UpdateOperatore3Args as UpdateOperatore3Args };
