/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore23WhereUniqueInput } from "./Operatore23WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteOperatore23Args {
  @ApiProperty({
    required: true,
    type: () => Operatore23WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore23WhereUniqueInput)
  @Field(() => Operatore23WhereUniqueInput, { nullable: false })
  where!: Operatore23WhereUniqueInput;
}

export { DeleteOperatore23Args as DeleteOperatore23Args };
