/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore23WhereInput } from "./Operatore23WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore23ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore23WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore23WhereInput)
  @IsOptional()
  @Field(() => Operatore23WhereInput, {
    nullable: true,
  })
  every?: Operatore23WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore23WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore23WhereInput)
  @IsOptional()
  @Field(() => Operatore23WhereInput, {
    nullable: true,
  })
  some?: Operatore23WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore23WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore23WhereInput)
  @IsOptional()
  @Field(() => Operatore23WhereInput, {
    nullable: true,
  })
  none?: Operatore23WhereInput;
}
export { Operatore23ListRelationFilter as Operatore23ListRelationFilter };
