/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore23WhereInput } from "./Operatore23WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Operatore23CountArgs {
  @ApiProperty({
    required: false,
    type: () => Operatore23WhereInput,
  })
  @Field(() => Operatore23WhereInput, { nullable: true })
  @Type(() => Operatore23WhereInput)
  where?: Operatore23WhereInput;
}

export { Operatore23CountArgs as Operatore23CountArgs };
