/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Operatore23Service } from "../operatore23.service";
import { Operatore23CreateInput } from "./Operatore23CreateInput";
import { Operatore23 } from "./Operatore23";
import { Operatore23FindManyArgs } from "./Operatore23FindManyArgs";
import { Operatore23WhereUniqueInput } from "./Operatore23WhereUniqueInput";
import { Operatore23UpdateInput } from "./Operatore23UpdateInput";

export class Operatore23ControllerBase {
  constructor(protected readonly service: Operatore23Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operatore23 })
  async createOperatore23(
    @common.Body() data: Operatore23CreateInput
  ): Promise<Operatore23> {
    return await this.service.createOperatore23({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operatore23] })
  @ApiNestedQuery(Operatore23FindManyArgs)
  async operatore23s(@common.Req() request: Request): Promise<Operatore23[]> {
    const args = plainToClass(Operatore23FindManyArgs, request.query);
    return this.service.operatore23s({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operatore23 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operatore23(
    @common.Param() params: Operatore23WhereUniqueInput
  ): Promise<Operatore23 | null> {
    const result = await this.service.operatore23({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operatore23 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperatore23(
    @common.Param() params: Operatore23WhereUniqueInput,
    @common.Body() data: Operatore23UpdateInput
  ): Promise<Operatore23 | null> {
    try {
      return await this.service.updateOperatore23({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operatore23 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperatore23(
    @common.Param() params: Operatore23WhereUniqueInput
  ): Promise<Operatore23 | null> {
    try {
      return await this.service.deleteOperatore23({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
