/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore17CreateInput } from "./Operatore17CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateOperatore17Args {
  @ApiProperty({
    required: true,
    type: () => Operatore17CreateInput,
  })
  @ValidateNested()
  @Type(() => Operatore17CreateInput)
  @Field(() => Operatore17CreateInput, { nullable: false })
  data!: Operatore17CreateInput;
}

export { CreateOperatore17Args as CreateOperatore17Args };
