/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore17WhereUniqueInput } from "./Operatore17WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class Operatore17FindUniqueArgs {
  @ApiProperty({
    required: true,
    type: () => Operatore17WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Operatore17WhereUniqueInput)
  @Field(() => Operatore17WhereUniqueInput, { nullable: false })
  where!: Operatore17WhereUniqueInput;
}

export { Operatore17FindUniqueArgs as Operatore17FindUniqueArgs };
