/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Operatore17WhereInput } from "./Operatore17WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Operatore17ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Operatore17WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore17WhereInput)
  @IsOptional()
  @Field(() => Operatore17WhereInput, {
    nullable: true,
  })
  every?: Operatore17WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore17WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore17WhereInput)
  @IsOptional()
  @Field(() => Operatore17WhereInput, {
    nullable: true,
  })
  some?: Operatore17WhereInput;

  @ApiProperty({
    required: false,
    type: () => Operatore17WhereInput,
  })
  @ValidateNested()
  @Type(() => Operatore17WhereInput)
  @IsOptional()
  @Field(() => Operatore17WhereInput, {
    nullable: true,
  })
  none?: Operatore17WhereInput;
}
export { Operatore17ListRelationFilter as Operatore17ListRelationFilter };
